# External Data

- The data can be downloaded from the below link http://data.iabac.org/exam/p2/data/INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls

In [2]:
import pandas as pd
# Importing data from the dataset
Emp_Per=pd.read_excel('INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls')
#Reading the first 3 rows
Emp_Per.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

# Processed Data

In [5]:
#Seting the target and predictor variables
X=Emp_Per.loc[:,'Age':'Attrition']
y=Emp_Per.loc[:,'PerformanceRating']

In [6]:
# Datasets for Modelling
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=5)

In [15]:
# data used for training
X

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,...,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
0,32,1,2,2,5,13,2,10,3,4,...,12,4,10,2,2,10,7,0,8,0
1,47,1,2,2,5,13,2,14,4,4,...,12,4,20,2,3,7,7,1,7,0
2,40,1,1,1,5,13,1,5,4,4,...,21,3,20,2,3,18,13,1,12,0
3,41,1,0,0,3,8,2,10,4,2,...,15,2,23,2,2,21,6,12,6,0
4,60,1,2,2,5,13,2,16,4,1,...,14,4,10,1,3,2,2,2,2,0
5,27,1,1,0,1,3,1,10,2,4,...,21,3,9,4,2,9,7,1,7,0
6,50,1,2,1,5,14,2,8,4,4,...,15,4,4,2,3,2,2,2,2,0
7,28,0,1,2,1,3,2,1,2,1,...,13,4,10,4,3,7,7,3,7,1
8,36,0,1,1,1,3,0,8,3,1,...,14,1,10,2,3,8,7,0,5,0
9,38,0,1,2,1,3,2,1,3,3,...,14,4,10,4,4,1,0,0,0,0
10,44,1,3,2,1,3,0,24,3,1,...,14,3,9,5,3,5,2,1,4,0
11,47,0,3,0,5,13,1,3,3,4,...,12,4,28,2,2,22,2,11,13,0
12,30,1,2,0,5,13,2,27,5,3,...,23,4,10,2,2,8,7,7,7,0
13,29,1,1,2,5,14,2,10,3,3,...,11,3,1,6,3,1,0,0,0,0
14,42,1,3,0,1,3,1,19,3,3,...,12,4,7,2,3,2,2,2,2,1
15,34,0,3,2,1,3,2,8,2,2,...,11,4,10,2,3,5,1,4,3,0
16,39,0,0,1,3,6,2,3,3,3,...,15,3,12,3,1,8,3,3,6,0
17,56,1,3,1,1,3,2,9,3,3,...,11,3,30,1,2,10,7,1,1,0
18,40,0,3,2,1,3,2,2,1,4,...,20,4,5,2,2,4,2,2,3,0
19,27,0,3,2,1,3,2,7,3,4,...,19,1,9,2,1,7,6,0,7,0
20,29,1,2,0,5,14,2,10,3,4,...,14,4,2,2,3,2,2,2,2,0
21,53,1,1,2,1,3,2,6,3,4,...,17,4,19,4,3,2,2,2,2,0
22,35,0,1,0,1,15,0,2,4,4,...,11,1,16,2,4,1,0,0,0,0
23,32,1,1,1,1,3,1,24,4,1,...,15,4,10,2,3,10,8,4,7,0
24,34,0,1,0,1,3,2,8,5,2,...,14,3,7,3,3,0,0,0,0,0
25,52,1,2,1,5,8,2,3,4,3,...,11,1,34,3,4,34,6,1,16,0
26,33,1,4,2,1,3,2,1,4,4,...,13,3,10,2,2,10,9,7,8,1
27,25,0,3,2,5,13,2,26,1,3,...,23,2,6,5,2,6,5,1,4,0
28,45,1,5,2,5,14,2,2,2,2,...,13,1,9,3,3,8,7,3,1,0
29,23,1,3,2,1,3,2,10,1,1,...,18,4,2,3,3,2,2,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,38,0,1,2,1,3,2,1,1,3,...,17,4,8,3,2,0,0,0,0,0
1171,43,1,3,0,1,15,1,9,5,4,...,13,2,10,3,3,8,7,4,7,0
1172,48,0,1,1,1,15,2,1,4,4,...,11,1,21,3,1,3,2,0,2,0
1173,44,0,1,2,3,6,2,1,4,1,...,11,2,10,1,4,2,2,0,2,0
1174,34,0,5,0,5,14,2,14,3,3,...,18,4,8,3,3,8,2,0,6,0
1175,27,1,2,0,5,14,2,2,1,3,...,11,2,5,3,3,4,3,0,2,1
1176,21,1,5,2,5,14,2,22,1,3,...,11,3,3,2,3,3,2,1,2,0
1177,44,1,4,1,1,15,2,3,4,4,...,12,1,26,2,4,2,2,0,1,0
1178,22,1,3,1,1,3,2,6,1,1,...,20,4,3,3,3,2,2,2,2,0
1179,32,0,1,1,1,3,2,9,4,1,...,12,4,6,2,2,6,4,0,5,0
1180,30,0,3,0,1,3,1,3,3,3,...,20,3,1,2,3,1,0,0,0,0
1181,34,1,1,1,1,15,2,1,5,2,...,12,4,10,4,2,10,9,8,8,0
1182,26,0,1,1,1,3,2,6,3,3,...,13,3,3,2,3,3,2,0,2,0
1183,37,1,4,1,1,3,2,3,3,3,...,15,3,10,2,3,10,7,7,8,0
1184,29,0,3,1,5,13,2,3,2,2,...,14,1,6,5,2,6,0,1,2,0
1185,35,1,1,2,1,15,2,6,4,2,...,13,2,17,3,3,17,11,11,8,0
1186,54,1,3,1,3,6,2,19,4,3,...,15,3,16,1,4,9,7,7,1,0
1187,36,1,3,0,1,3,2,9,2,2,...,11,3,13,2,3,3,2,0,2,0
1188,20,1,3,2,1,15,2,10,1,4,...,11,4,1,5,3,1,0,1,1,1
1189,33,1,1,2,1,15,1,3,3,1,...,11,1,10,3,3,10,8,9,7,1
1190,23,1,3,1,1,3,2,4,3,1,...,16,1,5,3,4,3,2,0,2,0
1191,25,1,1,1,5,13,2,8,3,4,...,22,3,4,4,3,3,2,1,2,0
1192,38,0,2,2,5,13,2,7,4,4,...,20,1,8,2,3,7,7,0,5,0
1193,29,1,1,0,1,3,1,1,4,2,...,18,4,10,5,3,10,7,2,8,0
1194,48,1,2,1,5,13,2,2,1,2,...,12,4,12,3,3,2,2,2,2,0
1195,27,0,3,0,5,13,1,3,1,4,...,20,2,6,3,3,6,5,0,4,0
1196,37,1,1,2,1,15,2,10,2,4,...,17,1,4,2,3,1,0,0,0,0
1197,50,1,3,1,1,15,2,28,1,4,...,11,3,20,3,3,20,8,3,8,0
1198,34,0,3,2,0,1,2,9,3,4,...,14,2,9,3,4,8,7,7,7,0
1199,24,0,1,2,5,13,2,3,2,1,...,14,1,4,3,3,2,2,2,0,1

In [22]:
#Data used for Testing
y

0       3
1       3
2       4
3       3
4       3
5       4
6       3
7       3
8       3
9       3
10      3
11      3
12      4
13      3
14      3
15      3
16      3
17      3
18      4
19      3
20      3
21      3
22      3
23      3
24      3
25      4
26      3
27      4
28      3
29      3
       ..
1170    3
1171    3
1172    3
1173    3
1174    3
1175    3
1176    3
1177    3
1178    3
1179    3
1180    4
1181    3
1182    3
1183    3
1184    3
1185    3
1186    3
1187    3
1188    3
1189    3
1190    4
1191    4
1192    4
1193    3
1194    3
1195    4
1196    3
1197    3
1198    3
1199    2
Name: PerformanceRating, Length: 1200, dtype: int64

In [19]:
#Data used for X_train
X_train

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,...,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
811,35,0,3,1,1,0,2,23,4,3,...,15,3,4,3,3,2,2,2,2,0
875,26,0,1,1,3,6,2,25,1,3,...,23,4,8,3,3,8,7,5,7,0
691,32,0,3,0,4,9,0,15,4,3,...,18,2,9,6,3,5,1,1,2,0
1187,36,1,3,0,1,3,2,9,2,2,...,11,3,13,2,3,3,2,0,2,0
657,27,0,3,2,5,13,2,2,2,1,...,14,2,9,5,2,8,7,0,7,0
1047,37,1,3,0,1,2,2,5,2,4,...,16,3,8,2,2,6,2,0,4,0
193,37,0,4,2,4,5,2,3,3,4,...,15,1,8,3,2,4,3,0,1,0
628,43,1,1,1,5,13,1,2,4,1,...,20,3,7,5,3,7,7,7,7,0
796,27,0,1,0,1,17,2,2,4,4,...,13,4,1,6,3,1,0,0,0,0
832,55,1,1,1,5,13,2,1,2,1,...,14,4,24,4,3,1,0,1,0,0
287,36,0,5,0,4,10,2,1,3,3,...,21,3,17,2,3,7,7,7,7,0
601,36,1,1,1,4,9,2,10,3,4,...,13,4,15,1,3,12,8,5,7,0
222,45,0,1,1,5,13,0,9,4,2,...,13,4,15,2,3,15,10,4,12,0
244,41,1,1,1,4,7,2,12,4,2,...,11,1,6,4,3,1,0,0,0,0
228,38,1,2,2,5,13,2,2,2,4,...,16,3,10,2,3,1,0,0,0,0
505,47,0,1,1,3,8,2,26,4,4,...,11,3,27,2,3,5,2,1,0,0
439,29,0,1,1,4,7,1,2,1,4,...,13,3,4,3,3,3,2,0,2,0
133,45,1,1,1,1,3,0,4,2,3,...,12,2,9,5,2,9,7,0,8,0
392,31,0,1,2,4,11,2,8,5,1,...,11,3,9,3,4,3,2,1,0,0
126,41,1,3,2,1,3,2,6,3,4,...,13,3,20,3,3,18,13,2,17,0
823,29,1,1,1,1,0,2,2,3,3,...,23,4,6,3,3,5,4,0,4,0
1150,37,0,5,2,1,3,2,1,3,2,...,17,4,12,3,4,6,5,1,2,0
533,32,1,3,0,2,4,2,2,3,4,...,13,3,10,4,2,9,5,1,6,0
247,27,1,1,1,4,12,2,6,3,4,...,13,3,4,0,3,4,2,2,2,0
349,34,0,3,2,5,13,2,15,2,3,...,12,4,10,6,4,10,8,9,6,0
212,33,0,3,2,4,12,1,29,4,1,...,22,2,14,4,3,13,7,3,8,1
1075,36,0,1,1,1,3,2,2,3,4,...,13,2,6,3,3,2,2,2,2,0
856,54,0,0,2,3,8,0,26,3,4,...,12,3,23,3,3,5,3,4,4,0
1006,49,0,1,2,1,3,1,10,4,3,...,11,4,22,4,3,3,2,1,2,0
779,24,0,4,0,1,3,0,11,2,1,...,18,4,5,5,2,4,2,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,56,0,2,1,5,13,2,11,5,4,...,16,3,6,3,3,0,0,0,0,0
1134,48,0,2,1,5,13,2,2,5,2,...,14,1,14,2,3,9,7,6,7,0
900,30,0,1,1,5,13,2,5,3,2,...,12,3,12,2,3,10,9,7,4,0
768,59,0,3,1,1,15,2,3,3,3,...,20,1,12,3,2,1,0,0,0,0
5,27,1,1,0,1,3,1,10,2,4,...,21,3,9,4,2,9,7,1,7,0
974,42,0,1,2,1,3,2,17,2,4,...,13,3,10,1,3,3,2,0,2,0
1168,42,0,1,1,1,3,2,2,4,3,...,13,2,10,4,3,10,2,2,2,0
103,32,1,1,2,1,3,2,25,4,1,...,24,3,1,2,1,1,0,0,1,1
210,55,1,1,1,4,9,1,2,1,4,...,18,2,23,4,3,3,2,1,2,0
41,38,0,1,2,1,3,1,2,4,1,...,12,4,17,2,3,15,7,4,12,0
377,43,0,3,2,4,12,2,6,3,1,...,14,1,20,3,1,20,7,1,8,0
146,29,0,1,2,1,3,2,10,3,4,...,20,3,3,5,3,0,0,0,0,1
1110,26,0,1,0,1,15,2,23,3,1,...,22,2,3,3,1,3,2,0,2,0
1089,31,0,3,1,1,3,2,7,2,2,...,12,2,13,5,1,13,10,3,12,0
205,26,1,3,1,4,7,2,1,2,1,...,16,1,6,2,3,5,3,1,3,0
1068,21,0,1,2,5,14,2,12,3,3,...,15,4,1,0,3,1,0,0,0,1
27,25,0,3,2,5,13,2,26,1,3,...,23,2,6,5,2,6,5,1,4,0
1104,60,0,1,1,1,3,2,7,3,1,...,11,4,33,5,1,29,8,11,10,0
1137,35,1,2,1,5,13,2,1,3,2,...,11,3,15,2,3,11,9,6,9,0
204,28,1,5,2,4,16,0,24,2,2,...,12,1,10,2,2,10,7,1,9,1
670,33,1,2,2,5,13,2,10,4,2,...,14,2,10,2,2,10,4,0,9,0
624,18,0,3,2,4,9,0,14,3,2,...,16,3,0,4,1,0,0,0,0,0
411,34,0,5,1,3,6,2,9,4,1,...,15,4,2,0,3,2,2,2,2,1
740,29,1,3,1,4,12,2,1,4,1,...,14,2,4,3,4,2,2,2,2,1
1032,27,1,1,2,5,13,2,2,3,4,...,11,1,5,3,3,5,4,0,4,0
73,44,1,3,2,1,3,2,4,3,4,...,12,4,10,2,2,5,2,2,3,0
1142,33,0,3,0,1,3,2,1,5,1,...,19,3,10,2,3,6,1,0,5,0
998,53,1,3,1,1,18,2,3,4,3,...,16,4,21,5,2,5,3,1,3,0
206,30,1,4,1,4,16,2,20,3,3,...,15,3,7,1,2,6,2,0,2,0
867,58,0,3,1,1,3,2,23,4,4,...,12,4,40,3,2,40,10,15,6,1

In [18]:
#Data used for X_test
X_test

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,...,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition
984,28,1,1,2,1,3,2,2,4,1,...,11,3,5,5,1,0,0,0,0,1
887,53,1,2,1,5,14,2,6,2,2,...,20,4,13,3,1,7,7,4,5,0
11,47,0,3,0,5,13,1,3,3,4,...,12,4,28,2,2,22,2,11,13,0
235,35,1,2,0,5,13,1,11,2,4,...,11,4,5,3,3,5,2,0,2,0
596,21,1,2,2,5,14,2,7,1,2,...,13,2,1,3,3,1,0,1,0,1
106,20,0,3,2,5,14,2,2,3,3,...,13,4,2,3,2,2,2,0,2,1
820,45,1,1,0,1,0,2,7,3,2,...,17,3,25,2,3,1,0,0,0,0
469,30,1,5,1,5,13,2,29,4,3,...,12,2,9,3,3,4,2,1,3,0
515,24,0,5,2,2,4,1,2,1,1,...,13,3,6,2,3,6,3,1,3,0
312,51,1,1,0,5,8,1,9,3,4,...,24,1,31,5,2,29,10,11,10,0
1066,40,1,2,1,5,13,2,22,2,3,...,12,1,8,6,3,6,4,1,0,1
34,26,0,1,0,1,3,1,1,2,1,...,14,1,5,2,3,2,2,2,0,0
346,35,1,1,2,4,12,1,4,4,3,...,11,2,9,3,3,9,6,1,1,0
782,53,0,4,0,1,15,2,5,3,3,...,11,4,26,3,2,14,13,4,8,0
567,32,1,1,2,5,13,2,1,2,1,...,15,2,10,2,3,0,0,0,0,1
915,50,1,3,1,1,3,2,1,3,3,...,15,4,5,2,2,3,2,0,2,0
688,34,1,2,2,5,13,2,1,3,1,...,21,1,14,3,2,14,8,2,1,0
583,49,0,2,2,5,13,2,11,4,4,...,12,3,8,1,4,5,1,0,4,0
514,35,1,3,0,5,13,2,15,2,1,...,14,4,7,2,2,2,2,2,2,1
166,48,1,1,2,4,16,2,4,4,3,...,14,2,27,3,3,15,11,4,8,0
655,40,1,1,0,4,9,2,1,4,1,...,11,1,22,3,3,19,7,11,16,0
1188,20,1,3,2,1,15,2,10,1,4,...,11,4,1,5,3,1,0,1,1,1
517,27,1,3,2,2,4,1,2,3,4,...,13,3,6,0,2,4,2,1,2,0
1022,31,1,5,1,1,3,2,5,4,3,...,12,3,6,4,3,5,2,0,3,0
149,50,1,3,0,1,15,2,1,2,4,...,22,3,32,1,2,5,4,1,3,0
552,43,1,3,1,5,13,2,2,3,4,...,17,1,10,3,3,10,9,8,8,0
40,37,0,1,0,1,3,2,10,1,4,...,13,2,6,3,2,5,3,4,3,0
344,34,1,1,0,4,5,2,9,3,4,...,11,4,10,0,2,9,7,1,6,0
760,26,0,4,2,5,14,2,5,3,4,...,18,4,5,2,3,4,2,0,0,0
559,41,1,0,1,3,6,0,4,3,3,...,19,2,10,4,3,3,2,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680,38,1,1,0,4,9,2,9,2,2,...,19,4,10,0,4,5,2,0,3,0
545,26,1,3,2,2,4,0,7,3,4,...,20,3,7,5,3,7,7,5,7,0
921,52,1,1,1,1,3,2,1,4,3,...,14,1,34,5,3,33,18,11,9,0
1049,31,0,3,2,1,2,2,7,4,3,...,14,3,11,2,2,11,9,4,10,0
434,47,0,3,1,5,13,2,14,3,3,...,17,3,11,4,2,5,4,1,2,0
458,33,1,1,1,4,7,2,28,4,2,...,12,2,15,3,3,15,14,5,7,0
486,34,1,5,1,2,4,1,10,4,4,...,14,2,8,3,2,8,2,7,7,0
492,44,0,3,0,2,4,2,7,3,2,...,14,4,23,4,2,22,7,1,10,0
1166,27,0,3,0,1,3,2,6,4,1,...,12,3,6,5,2,5,3,0,3,0
561,24,1,3,0,4,7,2,29,1,2,...,13,2,6,2,4,6,2,1,2,0
819,36,1,1,2,1,0,1,11,3,2,...,13,3,6,3,3,6,5,0,3,0
1012,35,1,2,1,5,13,2,16,3,3,...,15,3,12,3,2,11,9,6,9,0
542,53,1,3,1,2,4,2,24,4,2,...,15,3,11,2,3,4,3,1,2,0
203,46,0,1,0,4,16,2,8,4,4,...,23,1,19,2,3,16,13,1,7,0
932,49,1,1,0,1,18,0,18,4,4,...,15,1,7,0,3,7,7,1,7,0
284,42,1,3,1,3,6,0,2,5,4,...,16,1,10,3,4,4,3,0,3,0
446,35,0,1,2,4,9,2,16,3,4,...,19,4,11,3,1,11,8,3,3,0
573,30,0,5,2,4,9,1,2,4,4,...,16,4,10,2,3,9,7,0,7,0
556,26,1,3,1,4,7,2,17,4,4,...,15,3,3,3,4,3,2,0,2,0
791,50,1,2,1,5,14,2,3,2,1,...,14,3,3,2,3,3,2,0,2,1
1058,26,1,1,1,5,13,2,1,3,3,...,17,2,8,3,3,8,7,7,7,0
8,36,0,1,1,1,3,0,8,3,1,...,14,1,10,2,3,8,7,0,5,0
883,30,0,5,0,1,3,2,5,3,4,...,14,4,8,3,3,3,2,2,2,0
675,47,1,5,1,4,9,0,14,4,3,...,18,3,16,4,4,8,7,1,7,0
213,34,1,1,2,4,5,1,3,1,1,...,17,3,7,1,2,6,2,0,4,0
1087,40,0,3,1,1,3,2,2,3,2,...,22,2,20,3,3,1,0,0,0,0
672,39,0,1,1,5,13,0,21,4,1,...,19,3,10,1,3,3,2,1,2,0
807,35,1,3,1,1,17,0,11,2,3,...,13,3,10,3,3,4,0,2,3,0
390,31,0,1,2,5,14,1,1,4,2,...,12,2,1,3,3,1,0,0,0,1
198,36,0,3,2,4,10,2,12,5,4,...,11,2,15,2,2,14,8,7,8,0

In [21]:
#Data used for y_train
y_train

811     3
875     4
691     3
1187    3
657     3
1047    3
193     3
628     2
796     3
832     3
287     4
601     3
222     2
244     3
228     3
505     3
439     3
133     3
392     3
126     3
823     4
1150    4
533     3
247     3
349     3
212     2
1075    3
856     3
1006    3
779     3
       ..
676     3
1134    2
900     2
768     4
5       4
974     3
1168    3
103     3
210     3
41      3
377     2
146     4
1110    3
1089    3
205     2
1068    3
27      4
1104    3
1137    2
204     2
670     3
624     3
411     2
740     2
1032    3
73      3
1142    3
998     3
206     3
867     3
Name: PerformanceRating, Length: 900, dtype: int64

In [23]:
#Data used for y_test
y_test

984     3
887     2
11      3
235     3
596     3
106     3
820     3
469     3
515     2
312     4
1066    3
34      3
346     3
782     3
567     3
915     3
688     2
583     3
514     2
166     3
655     2
1188    3
517     3
1022    3
149     4
552     3
40      3
344     3
760     3
559     3
       ..
680     4
545     4
921     3
1049    3
434     3
458     2
486     3
492     2
1166    3
561     2
819     4
1012    3
542     2
203     4
932     3
284     4
446     3
573     3
556     3
791     3
1058    3
8       3
883     3
675     3
213     3
1087    4
672     2
807     3
390     3
198     3
Name: PerformanceRating, Length: 300, dtype: int64

In [28]:
# Deploying Model to use it in the real service
from sklearn.externals import joblib
joblib.dump(RFC,"Emp_Perf.ml")

['Emp_Perf.ml']

# Raw Data

In [29]:
Emp_Per

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,1,2,2,5,13,2,10,3,...,4,10,2,2,10,7,0,8,0,3
1,E1001006,47,1,2,2,5,13,2,14,4,...,4,20,2,3,7,7,1,7,0,3
2,E1001007,40,1,1,1,5,13,1,5,4,...,3,20,2,3,18,13,1,12,0,4
3,E1001009,41,1,0,0,3,8,2,10,4,...,2,23,2,2,21,6,12,6,0,3
4,E1001010,60,1,2,2,5,13,2,16,4,...,4,10,1,3,2,2,2,2,0,3
5,E1001011,27,1,1,0,1,3,1,10,2,...,3,9,4,2,9,7,1,7,0,4
6,E1001016,50,1,2,1,5,14,2,8,4,...,4,4,2,3,2,2,2,2,0,3
7,E1001019,28,0,1,2,1,3,2,1,2,...,4,10,4,3,7,7,3,7,1,3
8,E1001020,36,0,1,1,1,3,0,8,3,...,1,10,2,3,8,7,0,5,0,3
9,E1001021,38,0,1,2,1,3,2,1,3,...,4,10,4,4,1,0,0,0,0,3
10,E1001022,44,1,3,2,1,3,0,24,3,...,3,9,5,3,5,2,1,4,0,3
11,E1001024,47,0,3,0,5,13,1,3,3,...,4,28,2,2,22,2,11,13,0,3
12,E1001025,30,1,2,0,5,13,2,27,5,...,4,10,2,2,8,7,7,7,0,4
13,E1001027,29,1,1,2,5,14,2,10,3,...,3,1,6,3,1,0,0,0,0,3
14,E1001030,42,1,3,0,1,3,1,19,3,...,4,7,2,3,2,2,2,2,1,3
15,E1001035,34,0,3,2,1,3,2,8,2,...,4,10,2,3,5,1,4,3,0,3
16,E1001038,39,0,0,1,3,6,2,3,3,...,3,12,3,1,8,3,3,6,0,3
17,E1001040,56,1,3,1,1,3,2,9,3,...,3,30,1,2,10,7,1,1,0,3
18,E1001041,40,0,3,2,1,3,2,2,1,...,4,5,2,2,4,2,2,3,0,4
19,E1001042,27,0,3,2,1,3,2,7,3,...,1,9,2,1,7,6,0,7,0,3
20,E1001044,29,1,2,0,5,14,2,10,3,...,4,2,2,3,2,2,2,2,0,3
21,E1001047,53,1,1,2,1,3,2,6,3,...,4,19,4,3,2,2,2,2,0,3
22,E1001049,35,0,1,0,1,15,0,2,4,...,1,16,2,4,1,0,0,0,0,3
23,E1001050,32,1,1,1,1,3,1,24,4,...,4,10,2,3,10,8,4,7,0,3
24,E1001053,34,0,1,0,1,3,2,8,5,...,3,7,3,3,0,0,0,0,0,3
25,E1001054,52,1,2,1,5,8,2,3,4,...,1,34,3,4,34,6,1,16,0,4
26,E1001058,33,1,4,2,1,3,2,1,4,...,3,10,2,2,10,9,7,8,1,3
27,E1001059,25,0,3,2,5,13,2,26,1,...,2,6,5,2,6,5,1,4,0,4
28,E1001061,45,1,5,2,5,14,2,2,2,...,1,9,3,3,8,7,3,1,0,3
29,E1001062,23,1,3,2,1,3,2,10,1,...,4,2,3,3,2,2,0,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,E100940,38,0,1,2,1,3,2,1,1,...,4,8,3,2,0,0,0,0,0,3
1171,E100941,43,1,3,0,1,15,1,9,5,...,2,10,3,3,8,7,4,7,0,3
1172,E100942,48,0,1,1,1,15,2,1,4,...,1,21,3,1,3,2,0,2,0,3
1173,E100943,44,0,1,2,3,6,2,1,4,...,2,10,1,4,2,2,0,2,0,3
1174,E100944,34,0,5,0,5,14,2,14,3,...,4,8,3,3,8,2,0,6,0,3
1175,E100945,27,1,2,0,5,14,2,2,1,...,2,5,3,3,4,3,0,2,1,3
1176,E100947,21,1,5,2,5,14,2,22,1,...,3,3,2,3,3,2,1,2,0,3
1177,E100949,44,1,4,1,1,15,2,3,4,...,1,26,2,4,2,2,0,1,0,3
1178,E100953,22,1,3,1,1,3,2,6,1,...,4,3,3,3,2,2,2,2,0,3
1179,E100957,32,0,1,1,1,3,2,9,4,...,4,6,2,2,6,4,0,5,0,3
1180,E100958,30,0,3,0,1,3,1,3,3,...,3,1,2,3,1,0,0,0,0,4
1181,E100961,34,1,1,1,1,15,2,1,5,...,4,10,4,2,10,9,8,8,0,3
1182,E100964,26,0,1,1,1,3,2,6,3,...,3,3,2,3,3,2,0,2,0,3
1183,E100967,37,1,4,1,1,3,2,3,3,...,3,10,2,3,10,7,7,8,0,3
1184,E100968,29,0,3,1,5,13,2,3,2,...,1,6,5,2,6,0,1,2,0,3
1185,E100969,35,1,1,2,1,15,2,6,4,...,2,17,3,3,17,11,11,8,0,3
1186,E100976,54,1,3,1,3,6,2,19,4,...,3,16,1,4,9,7,7,1,0,3
1187,E100977,36,1,3,0,1,3,2,9,2,...,3,13,2,3,3,2,0,2,0,3
1188,E100979,20,1,3,2,1,15,2,10,1,...,4,1,5,3,1,0,1,1,1,3
1189,E100980,33,1,1,2,1,15,1,3,3,...,1,10,3,3,10,8,9,7,1,3
1190,E100983,23,1,3,1,1,3,2,4,3,...,1,5,3,4,3,2,0,2,0,4
1191,E100985,25,1,1,1,5,13,2,8,3,...,3,4,4,3,3,2,1,2,0,4
1192,E100987,38,0,2,2,5,13,2,7,4,...,1,8,2,3,7,7,0,5,0,4
1193,E100988,29,1,1,0,1,3,1,1,4,...,4,10,5,3,10,7,2,8,0,3
1194,E100990,48,1,2,1,5,13,2,2,1,...,4,12,3,3,2,2,2,2,0,3
1195,E100992,27,0,3,0,5,13,1,3,1,...,2,6,3,3,6,5,0,4,0,4
1196,E100993,37,1,1,2,1,15,2,10,2,...,1,4,2,3,1,0,0,0,0,3
1197,E100994,50,1,3,1,1,15,2,28,1,...,3,20,3,3,20,8,3,8,0,3
1198,E100995,34,0,3,2,0,1,2,9,3,...,2,9,3,4,8,7,7,7,0,3
1199,E100998,24,0,1,2,5,13,2,3,2,...,1,4,3,3,2,2,2,0,1,2